apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservicedep
  labels:
    app: authservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authservice
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: authservice
        tier: backend
        track: stable
    spec:
      containers:
      - name: authservice
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/directfn/authservice-gke:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"

